### ISSUE TITLE
Unable to run the sample app

### ISSUE THREAD

**Issue by macaroonable** [uhray/crud#6]
Hi, not sure whether i'm doing anything wrong here but when I run the `node app.js` I'm getting the following error after installing all the dependencies. 

```
hugie-personal-macbook-pro:express hugo$ node app.js
/Users/hugo/projects/express/app.js:11
  .entity("/users")
   ^

TypeError: crud.entity is not a function
    at Object.<anonymous> (/Users/hugo/projects/express/app.js:11:4)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

```
My app.js file is what's shown [here ](https://github.com/uhray/crud#simple-example) and my package.json includes the following: 
```
  "dependencies": {
    "crud": "0.0.28",
    "express": "^4.16.3",
    "express-resource": "^1.0.0",
    "mongoose": "^5.1.7",
    "node-crud": "^2.1.4"
```
Unsure whether it's a bug or whether I'm creating the express app wrongly.

**Comment by rthomps7** [comment]
@macaroonable 

The npm module is `node-crud` not `crud`. I updated that example to `require('node-crud')`, since that was a mistake, but the install needs to be `npm install node-crud` like the README says.
